export const wantToWrite = [
  'Article Writing',
  'Article Outline Writing',
  'Article Polishing',
  'Article Continued',
  'Title Generator',
  'Summarize',
  'Education',
  'Essay Writing',
  'Syllabus Writing',
  'Test Paper Generator',
  'Grammar Check',
  'Report',
  'Research',
  'Business',
  'SWOT Analysis',
  'OKR Generator',
  'Work Plan',
  'Resume',
  'Cover Letter',
  'Job Description',
  'PRD',
  'Contract',
  'Weekly Report',
  'Email',
  'Cold Email',
  'Reply Email',
  'Reject Email',
  'Promotion Email',
  'Newsletter Email',
  'Subject Lines',
  'Marketing',
  'Ad Campaign Plan',
  'Ad Headlines',
  'Ad Copy',
  'Product Ideas',
  'Product Description',
  'Social Media Ad',
  'Social Media Post',
  'Social Media Content',
  'Social Media Plan',
  'Social Media Strategy',
  'Social Media Report',
  'Social Media Management',
  'Social Media Marketing',
  'Social Media Marketing Plan',
  'SEO Keywords',
  'SEO Content',
  'SEO Plan',
  'SEO Strategy',
  'SEO Report',
  'SEO Management',
  'SEO Marketing',
  'SEO Description',
  'Life',
  'Life Plan',
  'Life Strategy',
  'Life Report',
  'Life Management',
  'Habit Plan',
  'Travel Plan',
  'Recipe',
  'Fitness Plan',
  'Meal Plan',
  'Mental Counseling',
  'Holiday Greetings',
  'Encyclopedia',
  'Dictionary',
  'Thesaurus',
  'Pet Training',
  'Creative',
  'Creative Writing',
  'Creative Plan',
  'ChatGPT Prompt',
  'Midjourney Prompt',
  'Story',
  'Story Outline',
  'Poem',
  'Movie Script',
  'Joke',
  'Other',
  'Product Description',
  'Comment',
  'Legal Solutions',
  'Dream Interpretation',
  'Speeches',
  'Notice',
]

export const whatRole = [
  'student',
  'teacher',
  'worker',
  'engineer',
  'manager',
  'developer',
  'designer',
  'marketer',
  'writer',
  'business',
  'freelancer',
  'lawyer',
  'customer',
  'doctor',
  'chef',
  'salesperson',
  'accountant',
  'artist',
  'psychologist',
  'entrepreneur',
  'architect',
  'journalist',
  'project',
  'data',
  'mechanical',
  'social',
  'pharmacist',
  'financial',
  'scientist',
  'PR',
  'advertiser',
  'editor',
  'novelist',
  'comedian',
  'speaker',
  'official',
  'coach',
  'electrician',
  'traveler',
  'commentariat',
  'mental adviser',
  'pet behaviorist',
  'KOL',
  'HR',
  'AI',
  'nurse',
  'expert',
  'investor',
  'blogger',
  'YouTuber',
  'dream interpreter',
  'tiktoker',
]

export const category = [
  {
    key: 1,
    name: 'Write',
  },
  {
    key: 2,
    name: 'Translate',
  },
  {
    key: 3,
    name: 'Grammar',
  },
  {
    key: 4,
    name: 'Coding',
  },
  {
    key: 5,
    name: 'Wikipedia',
  },
]
