import type { CodeTask } from '~/types'

export const wantToWrite = [
  'Article Writing',
  'Article Outline Writing',
  'Article Polishing',
  'Article Continued',
  'Title Generator',
  'Summarize',
  'Education',
  'Essay Writing',
  'Syllabus Writing',
  'Test Paper Generator',
  'Grammar Check',
  'Report',
  'Research',
  'Business',
  'SWOT Analysis',
  'OKR Generator',
  'Work Plan',
  'Resume',
  'Cover Letter',
  'Job Description',
  'PRD',
  'Contract',
  'Weekly Report',
  'Email',
  'Cold Email',
  'Reply Email',
  'Reject Email',
  'Promotion Email',
  'Newsletter Email',
  'Subject Lines',
  'Marketing',
  'Ad Campaign Plan',
  'Ad Headlines',
  'Ad Copy',
  'Product Ideas',
  'Product Description',
  'Social Media Ad',
  'Social Media Post',
  'Social Media Content',
  'Social Media Plan',
  'Social Media Strategy',
  'Social Media Report',
  'Social Media Management',
  'Social Media Marketing',
  'Social Media Marketing Plan',
  'SEO Keywords',
  'SEO Content',
  'SEO Plan',
  'SEO Strategy',
  'SEO Report',
  'SEO Management',
  'SEO Marketing',
  'SEO Description',
  'Life',
  'Life Plan',
  'Life Strategy',
  'Life Report',
  'Life Management',
  'Habit Plan',
  'Travel Plan',
  'Recipe',
  'Fitness Plan',
  'Meal Plan',
  'Mental Counseling',
  'Holiday Greetings',
  'Encyclopedia',
  'Dictionary',
  'Thesaurus',
  'Pet Training',
  'Creative',
  'Creative Writing',
  'Creative Plan',
  'ChatGPT Prompt',
  'Midjourney Prompt',
  'Story',
  'Story Outline',
  'Poem',
  'Movie Script',
  'Joke',
  'Other',
  'Product Description',
  'Comment',
  'Legal Solutions',
  'Dream Interpretation',
  'Speeches',
  'Notice',
]

export const whatRole = [
  'student',
  'teacher',
  'worker',
  'engineer',
  'manager',
  'developer',
  'designer',
  'marketer',
  'writer',
  'business',
  'freelancer',
  'lawyer',
  'customer',
  'doctor',
  'chef',
  'salesperson',
  'accountant',
  'artist',
  'psychologist',
  'entrepreneur',
  'architect',
  'journalist',
  'project',
  'data',
  'mechanical',
  'social',
  'pharmacist',
  'financial',
  'scientist',
  'PR',
  'advertiser',
  'editor',
  'novelist',
  'comedian',
  'speaker',
  'official',
  'coach',
  'electrician',
  'traveler',
  'commentariat',
  'mental adviser',
  'pet behaviorist',
  'KOL',
  'HR',
  'AI',
  'nurse',
  'expert',
  'investor',
  'blogger',
  'YouTuber',
  'dream interpreter',
  'tiktoker',
]

export const category = [
  {
    key: 1,
    name: 'Write',
    placeholder: 'What do you want to write?',
  },
  {
    key: 2,
    name: 'Translate',
    placeholder: 'What do you want to translate?',
  },
  {
    key: 3,
    name: 'Grammar',
    placeholder: 'What do you want to check?',
  },
  {
    key: 4,
    name: 'Coding',
    placeholder: 'What do you want to code?',
  },
  {
    key: 5,
    name: 'Wikipedia',
    placeholder: 'What do you want to Wikipedia?',
  },
  // {
  //   key: 6,
  //   name: 'Teacher and Improver',
  //   placeholder: 'Hello, what is your profession?',
  // },
]

export const language = ['Automatic', 'Việt nam', 'English', 'French', 'Spanish', 'Simplified Chinese', 'Traditional Chinese', 'Japanese', 'German', 'Russian', 'Arabic', 'Hindi', 'Portuguese', 'Italian', 'Korea', 'Dutch', 'Swedish', 'Norwegian', 'Danish', 'Finnish', 'Polish', 'Turkish', 'Indonesian', 'Malay']
export const advanced = {
  publish: ['Anywhere', 'Work', 'Email', 'Social Media'],
  tone: ['Neutral', 'Formal', 'Friendly', 'Casual'],
  format: ['Text', 'HTML', 'Markdown'],
  length: ['Short', 'Medium', 'Long'],
}

export const teacherAndImprover = [
  {
    value: 'spoken-english-teacher-and-improver',
    label: 'Spoken English Teacher and Improver',
  },
]

interface codingTaskOptionsType {
  value: CodeTask
  label: string
  placeholder: string
}

export const codingTaskOptions: codingTaskOptionsType[] = [
  {
    value: 'fix-code',
    label: 'Fix Code',
    placeholder: '',
  },
  {
    value: 'better',
    label: 'Make Better',
    placeholder: '',
  },
  {
    value: 'add-comment',
    label: 'Add Comment',
    placeholder: '',
  },
  {
    value: 'explain',
    label: 'Explain',
    placeholder: '',
  },
  {
    value: 'add-commit-change',
    label: 'Commit Change',
    placeholder: 'Run git diff in project & and copy to here',
  },
  {
    value: 'regex',
    label: 'Regex Generator',
    placeholder: 'Generate a regular expression that matches an email address.',
  },
]
